<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="CIPL1593QA" failures="1" tests="3" name="Test" time="19.955" errors="0" timestamp="2024-08-29T19:28:33 IST">
  <testcase classname="com.listener.ListenerclassDemo" name="testlogo" time="5.606"/>
  <testcase classname="com.listener.ListenerclassDemo" name="testappurl" time="3.05">
    <failure type="java.lang.AssertionError" message="expected [https://opensurce-demo.orangehrmlive.com/web/index.php/auth/login] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]">
      <![CDATA[java.lang.AssertionError: expected [https://opensurce-demo.orangehrmlive.com/web/index.php/auth/login] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]
at com.listener.ListenerclassDemo.testappurl(ListenerclassDemo.java:46)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testappurl -->
  <testcase classname="com.listener.ListenerclassDemo" name="homepagetitle" time="0.0">
    <skipped/>
  </testcase> <!-- homepagetitle -->
</testsuite> <!-- Test -->
